# Generated by Django 4.2.1 on 2023-06-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("AppCarrito", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppCarrito.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppCarrito.producto",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pedido",
            name="productos",
            field=models.ManyToManyField(
                through="AppCarrito.ProductoPedido", to="AppCarrito.producto"
            ),
        ),
    ]
