# Generated by Django 4.2.1 on 2023-06-23 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppCarrito", "0002_productopedido_alter_pedido_productos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="productos",
        ),
    ]
