# Generated by Django 4.2.1 on 2023-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCarrito", "0003_remove_pedido_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
